### ISSUE TITLE
E: Unable to locate package tshark Error: Failed to install tshark.

### ISSUE THREAD

**Issue by hatinati2** [FReak4L/packet-capture#1]
سلام وقت بخير

اررور زیر را می دهد

wget "https://raw.githubusercontent.com/FReak4L/packet-capture/main/packet_capture.sh" -O packet_captrue.sh && sed -i 's/\r$//' packet_captrue.sh && bash packet_captrue.sh
--2024-09-21 15:36:38--  https://raw.githubusercontent.com/FReak4L/packet-capture/main/packet_capture.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2635 (2.6K) [text/plain]
Saving to: ‘packet_captrue.sh’

packet_captrue.sh                    100%[===================================================================>]   2.57K  --.-KB/s    in 0s

2024-09-21 15:36:39 (13.2 MB/s) - ‘packet_captrue.sh’ saved [2635/2635]

Installing tshark...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package tshark
Error: Failed to install tshark.

**Comment by FReak4L** [comment]
سلام عزیزم. 
دلیلش میرور های سرورته 
میتونی به صورت دستی `tshark` نصب کنی اگه نصب نشد مطمئن باش از میرور هاس 
با این حال آپدیت بزن
`sudo apt update;apt upgrade;apt install tshark`
